---
- name: Set up load balancer 
  hosts: load_balancer
  gather_facts: false
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Back default configuration file
      copy: 
        remote_src: yes
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf.default
    - name: Create custom configuration file
      template: 
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded 
...
